[package]
name = "rgb-lib-ffi"
version = "0.1.0"
authors = [
    "Zoe Faltibà <zoefaltiba@gmail.com>",
    "Nicola Busanello <nicola.busanello@gmail.com>",
]
edition = "2021"
rust-version = "1.59.0"

[workspace]
members = [".", "rgb-lib-ffi-bindgen"]
default-members = [".", "rgb-lib-ffi-bindgen"]

[lib]
crate-type = ["staticlib", "cdylib"]
name = "rgblibffi"

[dependencies]
rgb-lib = { version = "0.1.9", path = "../" }
uniffi = { version = "0.22.0", features = ["builtin-bindgen"] }
uniffi_macros = { version = "0.22.0", features = ["builtin-bindgen"] }

[build-dependencies]
uniffi_build = { version = "0.22.0", features = ["builtin-bindgen"] }

[target.'cfg(target_os = "android")'.dependencies]
openssl = { version = "0.10", features = ["vendored"] }
